### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by 85nomar** [saki007ster/language-swig#4]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:550:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:172:43)
```

**Comment by ricardofbarros** [comment]
+1

**Comment by rakeshmenon** [comment]
Please fix this!

**Comment by saki007ster** [comment]
renamed the folder hope this solves the issue.

**Comment by kankaristo** [comment]
@saki007ster, please run `apm publish patch` so that the package can be updated in Atom.

**Comment by fbbdev** [comment]
@saki007ster please publish this!

**Comment by saki007ster** [comment]
This is now [published](https://atom.io/packages/language-swig)
